### ISSUE TITLE
Minor bug in preprocess_rollout.py

### ISSUE THREAD

**Issue by robertburbidgedata** [MolecularAI/aizynthfinder#1]
When re-running preprocess_rollout.py, if the library file specified in default_training.yml exists and library_headers doesn't include 'template_code' then it fails in _save_unique_templates because in this case template_code would be set in _filter_dataset which isn't called and when the library is read in we have 'names=config["library_headers"]', so the template_code column isn't read even if it's present. The workaround is obviously to delete the library file whenever I edit the raw library file and re-run; but if I forget, the error is only caught after the three preceding steps, which take some time on a large raw library.

**Comment by SGenheden** [comment]
Thanks for the feedback.
Just to get it right: you are defining your own `library_headers` that does not include the "template_code"? Why can't you add it to the `library_headers`?  Then the template codes would be read in when you are re-running the script. 
Another solution, would be to add a check for the `template_code` column in the library file and if it isn't there, re-compute it. But I would prefer that the "template_code" is in `library_headers`, if it is possible - because then the template codes only need to be computed once.

**Comment by robertburbidgedata** [comment]
Yes, I see now. I left it out because the online docs indicated to modify library_headers to match the columns in the raw template library and I didn't have this column (which I now see is generated when creating the template library). One alternative is to leave "template_code" out of library headers, modify names in _filter_dataset at line 28 of preprocess_rollout.py and add "template_code" to names at line 74.
