### ISSUE TITLE
Retraining Aizynthfinder 

### ISSUE THREAD

**Issue by vmarar** [MolecularAI/aizynthfinder#10]
Hi! So I tired retraining aizynthfinder on reactions sources from Maestro. We created reaction smiles format, put it through rxnmapper(atom mapping program) and then through rdchiral for the retro templates. I put it through preprocess_rollout and training. But when I used, it showed errors and wasn't able to process many of the compounds I put through(only able to process 99 of 395 compounds). I have all the necessary columns for the training file, and followed the documentation for training. Any input on why this might be happening?

**Comment by SGenheden** [comment]
Thanks for your feedback.
It is however impossible for me to say anything about your issue unless you provide more information: can you paste in an error trace? can you provide examples of exact input that is causing your issue and the exact command you were trying to use?

**Comment by vmarar** [comment]
The error I received when running the batch processing after using our newly trained model and unique_templates was ChemicalParserException : Number of reactants provided does not match number of reactant templates is this a issue with the model or with the unique_templates ? Thanks

**Comment by SGenheden** [comment]
With the limited information you are providing, I can at most give educated guesses.

First assumption I make is that you when say you are "running the batch processing", you mean that you are running the tree search using the aizynthcli tool. 

The exception you are seeing ChemicalParserException comes to the best of my knowledge from the application of a template onto a product. Since we are doing the application in the retro order, what the exception thinks is a reactants is actual the product. So this exception is raised when the number of products and the number of templated molecules are mismatched. Since I don't see how the number of products can be anything but 1 in the tree search, it must mean that you have templates that doesn't have 1 product. 

To dig further into this from my side, you need to
* Show me exactly what line of code where the exception is coming from
* Give me some input data to look at, such as a SMARTS/SMIRKS template string and a molecule SMILES

**Comment by A-Thakkar** [comment]
Hi all,

Samuel has essentially covered it. The error originates from rdkit and not the model or tree search. The templates should have only one 'reactant' and 'n products' as they are retro templates. 

 The error occurs if you have specified the templates incorrectly. If it was me I would first check all the templates to ensure only one reactant in the retro template. It could be as simple as reversing all the templates you have. 

Second if there are multiple species on either side of the reaction, there is something wrong with the template extraction you have used or you have not filtered your reaction dataset for reactions that lead to only one product (which is more likely).

Hope it helps,

Amol

**Comment by A-Thakkar** [comment]
You can also check your templates reproduce the data they were generated from by taking each of the templates and applying them to their product from which they were extracted. If you regenerate the reactants in the dataset then you can verify the templates work.

**Comment by vmarar** [comment]
Thank you! That was exactly the issue we used a specific unimolecular reaction that after it was put through atom mapping and rdchiral, the reactions came out with multiple reactants which corrupted our unique_template file. Thanks again for all the help!
