### ISSUE TITLE
Is there any code provided to retrain the template applicability filter policy?

### ISSUE THREAD

**Issue by queliyong** [MolecularAI/aizynthfinder#100]
Hi, illuminated by the paper, "Artificial applicability labels for improving policies in retrosynthesis prediction", I wanna retrain the template applicability filter policy using USPTO data to enhance the ability to find routes. But I did not find the source code of this paper.Thank u for any help.

**Comment by SGenheden** [comment]
The code for this paper was never published, and is currently not in a stage that is nice for someone to use. I would suggest trying to implement it from scratch rather than build upon some of our old code.
With that said, I must say I am unsure if it will actually help that much with route finding. I don't think that was clearly shown.

**Comment by queliyong** [comment]
OK.Thanks a lot.
