### ISSUE TITLE
Steps "None" are displayed (Jupyter)

### ISSUE THREAD

**Issue by DocMinus** [MolecularAI/aizynthfinder#13]
After a fresh install (new machine; Ubuntu 18 LTS), I had some issues (a & b I mentioned in case they are related to Steps "None", though b shouldn't affect it)
Using Python 3.7.5 as base, conda environment. 

a) aiohttp 3.6.3 requires yarl<1.6.0,>=1.0, but you have yarl 1.6.2 which is incompatible.
b) despite GPU & no errors in TF install, there is a dlerror missing missing libcudnn.so.8 . and some follow-up libraries. Python switches to CPU based TF.  Not fun, but acceptable for now.

The app from within Jupyter seems to work, though I don't see any steps after the analysis is finished. Using your example smiles, starting materials are displayed, but no reactions schemes.
"None" is displayed.

From previous versions, I don't expect this to be correct behavior?

**Comment by SGenheden** [comment]
Thanks for use the tool.
For the "minor" point:
a) This comes from the fact that conda or pip couldn't resolve dependencies correctly. You can try to do `python -m pip install "yarl<1.6.0"`. But maybe there is another package that wants yarl 1.6.2. If the program runs, it runs. I wouldn't worry too much about this.
b) Depending on the OS, you might have to install additional libraries to have TF work with the GPU. There is most likely Stack overflow threads about this. However, if you are not intending to train any new models, the CPU version of TF will work very well.

For the bigger issue, I assume you pressed the "Show reactions" button in the Jupyter notebook and instead of showing the routes it just displayed None. The "None" message is of course not very informative - but it comes from a very specific failure in the code: the generation of the images using the graphviz library. 

So the first thing I want you to check is if the `dot` command is in your path. 
Open up a terminal and type `which dot`. 
If the `dot` command isn't found you need to make sure that graphviz was installed correctly. 

(I will make sure to make this "error message" clear in a future release)

**Comment by DocMinus** [comment]
Thanks. 
I got yarl 1.6.0 now installed, didn't think of downgrade possibility. (used conda, I prefer that whenever I can over pip).
I suspected graphviz, but since I see starting materials I didn't connect that really. 

`which dot` gives 
/home/alex/anaconda3/envs/aiz/bin/dot
(aiz is the conda ve for this)
I also added 
`export PATH=$PATH:/home/alex/anaconda3/envs/aiz/lib/graphviz`
but that doesn't make a difference, which still points to the above.

Maybe one could put a hardlink to the bin folder?

**Comment by SGenheden** [comment]
Thanks for checking that dot/graphviz was installed properly.
I realized that the setup.py didn't properly packaged some non-python files that are necessary to generate the route images.
I have now pushed a bugfix release. So try to re-install aizynthfinder
```
python -m pip uninstall aizynthfinder
python -m pip install https://github.com/MolecularAI/aizynthfinder/archive/v2.2.1.tar.gz 
```
and let me know if that solves your problem.

**Comment by DocMinus** [comment]
So there is definitely a difference between Windows and Linux. 
A new Win10 Conda env with your instructions worked. I tested with Py3.6 (just in case).

The same on Linux (both seem to have used your 2.2.1 version unknowingly), and it doesn't work. It complains about Rdkit - which ended up as 2018 version(!). Seemed to get downgraded to a conda forge version. I ran a manual upgrade again, and it used rkdkit channel to V2020. 
But there are more complaints about other compatibilities (e.g. TF), that it won't work (python command line check). Something breaks and the aizyntfinder stuff isn't found. (I tried the uninstall and reinstall, no difference).

Checked the above mentioned py3.8 install using the unistall and reinstall, but it's the same issue.
Rdkit becomes downgraded? Ensured Rkdit upgrade, but the again something else breaks.

Again, ok on Windows, not on Linux.

**Comment by SGenheden** [comment]
So if I understand you correctly, you have managed to obtain pictures of routes on both Linux and Windows - right? 
Getting all the dependencies to work together is also something I struggle with sometimes, for me it usually is best to remove the virtual environment and start over.
With that said, it is slightly out of my responsibility to support installation of dependencies and all possible platforms - for that you probably find a better answer on Stack Overflow.
So if images of routes can be displayed on your machine, I will close this issue. 
And lastly a big thank you for using this tool and thereby exposing a sever bug!

**Comment by DocMinus** [comment]
Yes, now it works on both systems. But the Linux one isn't that obvious.
And all attempts were done with new environments. 
So, yes, we can close this. Cheers.
