### ISSUE TITLE
Python and rdkit versions

### ISSUE THREAD

**Issue by robertburbidgedata** [MolecularAI/aizynthfinder#3]
As of today (14-Aug-20), rdkit reports that it is not compatible with the latest Python, 3.8 (but see https://github.com/brsynth/rdkit if you're interested). Also, the default conda install (at least on my system) installs rdkit 2017.09.1, and training.py fails with an ImportWarning. This set-up worked fine:
conda create -n AiZynthFinder python=3.6 tensorflow-gpu=2.2.0 graphviz
conda install -n AiZynthFinder -c rdkit rdkit=2019.09.1 -y

**Comment by SGenheden** [comment]
Thanks for the feedback.
I will update README.md so that it only specifies python 3.6 or 3.7
The default rdkit version seems to differ between OS and python version. When I used python 3.7 I got rdkit-2020.03.2.0 on Linux, Windows 10 and Mac OS Catalina. But when I used python 3.6 I got rdkit-2017.09.3.0 on the MacOS Catalina, but e.g. rdkit-2018.03.2.0 on the Linux machine. 
The pure RDKit functionality in aizynthfinder should work with 2017.09.3, but RDChiral specifies a requirement > 2019. So I have updated the command in the README.md to ` conda install -c rdkit "rdkit=>2019.09.1"`
