### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by lukasfriedrich91** [MolecularAI/aizynthfinder#30]
Hey everyone,

I got the following error message  when trying to execute aizynthfinder on a linux workstation with an older OS:

```
from sklearn.cluster import AgglomerativeClustering
  File "/SW/python/miniconda3/x86_64/envs/aizynth-dev/lib/python3.7/site-packages/sklearn/__init__.py", line 83, in <module>
    from .utils._show_versions import show_versions
  File "/SW/python/miniconda3/x86_64/envs/aizynth-dev/lib/python3.7/site-packages/sklearn/utils/_show_versions.py", line 12, in <module>
    from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: dlopen: cannot load any more object with static TLS
```
But it works on newer linux workstations. 

My assumptions is that the error is related to the import order of sklearn and tensorflow. 
If someone else encounter this, a workaround would be to add `import sklearn` to ` aizynthfinder/interfaces/aizynthapp.py` and `aizynthfinder/interfaces/aizynthcli.py` before the specific aizynthfinder imports.

**Comment by SGenheden** [comment]
Thanks for the feedback @lukasfriedrich91 

In order to get sklearn imported before tensorflow - it should be imported in the `aizynthfinder.utils.logging` module. Care has been taken so that this module is imported first in the application, which leads to `tensorflow` being one of the first packages to be imported so that TF warning messages can be suppressed. 

I will take it upon me to introduce this fix in a feature release.

**Comment by SGenheden** [comment]
I believe this was fixed in this [commit](https://github.com/MolecularAI/aizynthfinder/commit/51864ef8a1dc3501d60d21ddb4d71d392f47b045)
It is still just on master so to use it you need to clone the repository, I will prepare a release if necessary.

**Comment by SGenheden** [comment]
Included in latest release.
