### ISSUE TITLE
Could not Reorder by 'Sum of prices' in the GUI?

### ISSUE THREAD

**Issue by queliyong** [MolecularAI/aizynthfinder#31]
Hi. I wanna reorder by 'Sum of prices' to show reactions, but there seems no such item in the drop down list. And I also notice that there is no price information in the provided zinc_stock.hdf5 file. Do I need to modify the source code of scoring.py or stock.py in a folder named 'context'  besides adding price information to the stock file? Any help would be appreciated.

**Comment by SGenheden** [comment]
Thanks for your feedback.

The "Sum of prices" scorer is not added by default to the drop-down. In order to add it you can to something like this

```
from aizynthfinder.interfaces import AiZynthApp
from aizynthfinder.context.scoring import PriceSumScorer
app = AiZynthApp("my_config.yml", setup=False)
app.finder.scorers.load(PriceSumScorer(app.finder.config))
app.setup()
```

The reason it is not added by default, is because none of the stock query files supports pricing (as of yet). This is the first time someone outside AZ has asked about this :-)

If you add price information to the ZINC hdf5-file, in a column you could write your own stock query class (here is the general guide for it: https://molecularai.github.io/aizynthfinder/stocks.html)

Here is a sketch for it (I haven't tested the code):

```
from aizynthfinder.context.stock import StockQueryMixin
class InMemoryInchiKeyQueryWithPrices(StockQueryMixin):
    def __init__(self, filename: str) -> None:
        ext = os.path.splitext(filename)[1]
        stock = pd.read_hdf(filename, key="table")
        self._inchi_keys = list(stock["inchi_key"].values)
        self._prices = list(stock["price"].values)
    def __contains__(self, mol: Molecule) -> bool:
        return mol.inchi_key in self._inchi_keys
    def __len__(self) -> int:
        return len(self._inchi_keys)
    def price(self, mol) -> float:
        try:
            return self._prices[self._inchi_keys.index(mol.inchi_key)]
       except ValueError:
           raise StockException("Cannot compute price")
``` 

There could be more efficient way to do the look-up, but you get the idea. 

If you proceed with the implementation, and you are happy with it, please consider making a PR out of it. Don't hesitate to ask for more clarification.

**Comment by queliyong** [comment]
Thanks for your guidance. I'll try and make a feedback soon.
