### ISSUE TITLE
Graphviz installation description in Readme

### ISSUE THREAD

**Issue by DocMinus** [MolecularAI/aizynthfinder#4]
Installation on Windows worked as described, including Graphviz.
On Linux (2 different machines, Ubuntu 18 resp. 20) Graphviz installs but is not registered. Seems to be a rather common issue with Graphviz in particular. 
suggestions are to install with either

conda install -c anaconda graphviz 
or
conda install python-graphviz

I personally only got it to work with on Linux with
 
pip install graphviz
(which isn't preferred for separate environments).

My suggestion is to update the Readme with at least with a comment, thank you.

**Comment by SGenheden** [comment]
Thanks for your feedback.
I know Graphviz isn't the easiest to work with, and I have had issues with it previously.
However those issues arose because I was trying to use a python package like graphviz or pydot.
Then I skipped those packages and call `neato` and `dot` executables directly.
So installing with `pip` installs the python package not the executables. Similarly with `conda install python-graphviz`
So the only option that should do what is necessary is the `conda install -c anaconda graphviz`. Perhaps the default channel did not have a build for your OS. 
I will update the README with a comment as you suggested.

**Comment by Awametox** [comment]
> .......
> I will update the README with a comment as you suggested.

👍 
Cheers.

**Comment by DocMinus** [comment]
>.....
> I will update the README with a comment as you suggested.

👍 
Cheers!
