### ISSUE TITLE
How to train a reaction involving two simultaneous reaction steps?

### ISSUE THREAD

**Issue by queliyong** [MolecularAI/aizynthfinder#41]
![FB991182-E2F3-40de-9705-950577FFC488](https://user-images.githubusercontent.com/56716710/130171321-e46db291-2a7e-436a-956d-8ab4d98dab44.png)
Hi,
I extracted this reaction's retro template by rdchiral, as follows:
'[OH;D1;+0:2]-[c:1].[OH;D1;+0:4]-[c:3]>>[c:1]-[O;H0;D2;+0:2]-C-c1:c:c:c:c:c:1.[c:3]-[O;H0;D2;+0:4]-C-c1:c:c:c:c:c:1'

Obviously, the template has two products, It can not be used to train the reaction. Any idea to train this type of reaction? Thank U very much.
The reaction smiles is 'CC(C)(C)C1=CC(C2=C(CCCC3)C3=CC4=C2CCCC4)=C(OCC5=CC=CC=C5)C(C6=CC(C(C)(C)C)=CC=C6OC[C@@h]7CCCC[C@@h]7COC8=CC=C(C(C)(C)C)C=C8C9=CC(C(C)(C)C)=CC(C%10=C(CCCC%11)C%11=CC%12=C%10CCCC%12)=C9OCC%13=CC=CC=C%13)=C1>>OC1=C(C2=C(CCCC3)C3=CC4=C2CCCC4)C=C(C(C)(C)C)C=C1C5=CC(C(C)(C)C)=CC=C5OC[C@@h]6CCCC[C@@h]6COC7=CC=C(C(C)(C)C)C=C7C8=CC(C(C)(C)C)=CC(C9=C(CCCC%10)C%10=CC%11=C9CCCC%11)=C8O'

**Comment by SGenheden** [comment]
Thank you for your feedback, but...

This seems to be a problem with RDChiral being unable to create proper template. The reaction itself is a "simple" transformation reaction, and only has one product and one reactant, even though the template has two of each. Presumably because the molecule is symmetric.

I have encountered this a few times, and I have just simply removed this example from the template library. 

Alternatively, you can bring up the discussion with the developers of RDChiral.

**Comment by queliyong** [comment]
> Thank you for your feedback, but...
> 
> This seems to be a problem with RDChiral being unable to create proper template. The reaction itself is a "simple" transformation reaction, and only has one product and one reactant, even though the template has two of each. Presumably because the molecule is symmetric.
> 
> I have encountered this a few times, and I have just simply removed this example from the template library.
> 
> Alternatively, you can bring up the discussion with the developers of RDChiral.

Get it. Thank U for your patient reply.
