### ISSUE TITLE
Route starts to cycle when run search complicated target compound.

### ISSUE THREAD

**Issue by queliyong** [MolecularAI/aizynthfinder#47]
![zishanchun-official_length12](https://user-images.githubusercontent.com/56716710/137276282-548f7c3f-8ce6-4199-b7ac-1bc4a41e3dde.png)

Hi, I found that when the target compound is complicated, the route inclines to cycle, just like the compounds marked by the red cycle. how to solve it? how to force the mcts to break the large compound marked by the red cycle into smaller molecules. thank you.
the target compound is Paclitaxel.

**Comment by SGenheden** [comment]
Hello,

Which version of aizynthfinder are you using? The issue that molecules are regenerated in the MCTS should have been fixed in the latest release (3.0.0). 

That is a tough target to break down. I wouldn't image that there are any templates that could completely break down the ring systems. This seems to be partially a natural product, and from Googling I can see that the total synthetic pathway is heavily researched. The ML model used to break down molecules into pre-cursors are based on historical data, and if there is not historical data recorded for similar compounds, the algorithm will not be able to solve it.
